name: My Second Workflow/Exploring Variables and Secrets

#on: push 

on:
  workflow_dispatch:

jobs:
    first_job: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Use environment variables 
          run: echo ${{ vars.CODE_NAME }}
        