name: My First Workflow

on: push

jobs:
    first_job: 
      runs-on: ubuntu-latest
      steps:
        - name: Welcome Job
          run: echo " my first GitHub Action Job"
        - name: Second Job
          run: echo "/etc/hosts"