name: My First Workflow

on: push

jobs:
    first_job: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Welcome Job
          run: echo " my first GitHub Action Job"
        - name: Second Job
          run: |
            echo "/etc/hosts"
            date
        - name: Generate ASCII Artwork
          run: |
            sudo apt-get install cowsay -y 
            cowsay -f dragon "Run for cover, I am a dragon....RAWR" >> dragon.txt
        - name: Upload Build Artifact
          uses: actions/upload-artifact@v3
          with:
            name: dragon-text-file
            path: dragon.txt
    second_job:
      needs: [first_job]
      runs-on: ubuntu-latest
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v3
          with:
            name: dragon-text-file
        - name: Read Dragon Text File
          run: cat dragon.txt